[".goto.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/iridakos/goto/master/goto.sh"
    refreshPeriod = "720h"

[".local/share/bash-completion/completions/git"]
    type = "file"
    url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash"
    refreshPeriod = "720h"

[".local/share/bash-completion/completions/chezmoi"]
    type = "file"
    url = "https://raw.githubusercontent.com/twpayne/chezmoi/master/completions/chezmoi-completion.bash"
    refreshPeriod = "720h"

[".local/share/fonts"]
    type = "archive"
    stripComponents = 1
    url = "https://github.com/source-foundry/Hack/releases/download/v3.003/Hack-v3.003-ttf.zip"
    refreshPeriod = "0"
