[".local/share/nvim/site/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

[".goto.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/iridakos/goto/master/goto.sh"
    refreshPeriod = "720h"

[".local/share/bash-completion/completions/git"]
    type = "file"
    url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash"
    refreshPeriod = "720h"

[".local/share/bash-completion/completions/chezmoi"]
    type = "file"
    url = "https://raw.githubusercontent.com/twpayne/chezmoi/master/completions/chezmoi-completion.bash"
    refreshPeriod = "720h"

["dlang/install.sh"]
    type = "file"
    url = "https://dlang.org/install.sh"
    refreshPeriod = "168h"
