[".goto.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/iridakos/goto/master/goto.sh"
    refreshPeriod = "720h"

[".local/share/bash-completion/completions/git"]
    type = "file"
    url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash"
    refreshPeriod = "720h"

[".local/share/bash-completion/completions/chezmoi"]
    type = "file"
    url = "https://raw.githubusercontent.com/twpayne/chezmoi/master/completions/chezmoi-completion.bash"
    refreshPeriod = "720h"

[".local/share/bash-completion/completions/mise"]
    type = "file"
    url = "https://raw.githubusercontent.com/jdx/mise/main/completions/mise.bash"
    refreshPeriod = "720h"

[".local/share/bash-completion/completions/tmux"]
    type = "file"
    url = "https://raw.githubusercontent.com/imomaliev/tmux-bash-completion/master/completions/tmux"
    refreshPeriod = "720h"
