[".local/share/nvim/site/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

[".goto.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/iridakos/goto/master/goto.sh"
    refreshPeriod = "720h"
