[tools]
chezscheme = "latest"
restic = "latest"
watchexec = "latest"
"ubi:junegunn/fzf" = "latest"
"ubi:twpayne/chezmoi" = "latest"
usage = "latest"

[settings]
go_default_packages_file = "/home/steveno/.config/mise/default-go-packages"
