import = [
    "~/.config/alacritty/themes/everforest.toml"
]

[font]
normal.family = "IBM Plex Mono"
bold.family = "IBM Plex Mono"
italic.family = "IBM Plex Mono"
bold_italic.family = "IBM Plex Mono"
size = 13.0
